### PR TITLE
Wide Array of Fixes

### PR DESCRIPTION
**Pull request by ronhowe**
Minor and major corrections to align with JSON files.

### CODE REVIEW

**Review by DevoKun — CHANGES_REQUESTED** [review]
The files `Images-HT/listmd5`, `Images-HT/listmd5.bz2`, `latest.zip`, and `version.dat` are all get updated automatically by the GitHub workflow. The differences between those files is blocking the merge. If you can resubmit your pull request without those files included we can make the merge.

**Comment by ronhowe** [comment]
> The files `Images-HT/listmd5`, `Images-HT/listmd5.bz2`, `latest.zip`, and `version.dat` are all get updated automatically by the GitHub workflow. The differences between those files is blocking the merge. If you can resubmit your pull request without those files included we can make the merge.
> 
> To avoid running the workflow which automatically updates those files in your fork, work from a branch that is not named `master`.

Sounds good.  Working on it.

**Comment by ronhowe** [comment]
How about this?  I have a tough time with merge conflict resolution, especially on binary files.

**Comment by ronhowe** [comment]
Also, I'll have one more PR *after* this one.  I'll do that from a separate branch in my fork now that I know.

These changes will make it easy for me to run my PowerShell to convert JSON files to CDF files (and finally make it easy to generate Set 13 support).

**Comment by ronhowe** [comment]
I'm going to close this PR and ensure everything is good against a slew of changes in flight over in the JSON repo.

**Pull request closed without merging**
