### PR TITLE
Parity

### PR DESCRIPTION
**Pull request by ronhowe**
Cleaned up PR.

### CODE REVIEW

**Comment by ronhowe** [comment]
If this PR can get approved, I would be unblocked from submitting a Set 13 support PR.

**Comment by ronhowe** [comment]
I have a Set 13 commit ready for a forthcoming PR, but need this PR approved so I can cleanup some of the merge issues it will cause with my set-13 branch.

**Comment by DevoKun** [comment]
I am pulling down the changes to review locally.

**Comment by ronhowe** [comment]
> I am pulling down the changes to review locally.

Sounds good.  Keep me honest.  If there are fixes that need to be made, I'll make them.

Thanks for doing this.  Looking forward to getting Set 13 to you a.s.a.p.

**Review by DevoKun — COMMENTED** [review]
Please do not include any of the auto-generated fils in change requests. Automatically generated files include:
* `Images-HT/listmd5`
* `Images-HT/listmd5.bz2`
* `latest.zip`
* `version.dat`

**Comment by DevoKun** [comment]
I managed to review `dark.cdf`. Here are my comments:


You are removing data from Aurra Sing:
```
Permanent Weapon, Episode I\n\nLore: Bounty hunter. Assassin.\n\nText: Permanent weapon is •Aurra Sing's Blaster Rifle (may target a character for free; if targeting a Jedi, draw two destiny, otherwise draw destiny; target hit, and its forfeit = 0, if total destiny +1 > defense value).
```

You have removed `•Aurra Sing With Blaster Rifle (AI) (2)`, the Aurra Sing alternate image.

Before changing `DARK JEDI MASTER` to `Dark Jedi Master` we should verify that `holotable.exe` is compatible with this change.

Does `holotable.exe` support `Icons: Defensive Shield` icons? I see you are changing it from `Icons: Defensive Shields`.

There are some places where you are changing `Set: Virtual Defensive Shields` to `Icons: Defensive Shield`, I believe that is a bulk-change mistake.


You are removing `Ability, Ability, Ability (V) (3)`
```
card "/starwars/Virtual0-Dark/t_abilityabilityability" "•Ability, Ability, Ability (V) (3)\nDark

**Comment by DevoKun** [comment]
I will review `light.cdf` at a future time.

**Comment by ronhowe** [comment]
> I managed to review `dark.cdf`. Here are my comments:
> 
> You are removing data from Aurra Sing:
> 
> ```
> Permanent Weapon, Episode I\n\nLore: Bounty hunter. Assassin.\n\nText: Permanent weapon is •Aurra Sing's Blaster Rifle (may target a character for free; if targeting a Jedi, draw two destiny, otherwise draw destiny; target hit, and its forfeit = 0, if total destiny +1 > defense value).
> ```
> 
> You have removed `•Aurra Sing With Blaster Rifle (AI) (2)`, the Aurra Sing alternate image.
> 
> Before changing `DARK JEDI MASTER` to `Dark Jedi Master` we should verify that `holotable.exe` is compatible with this change.
> 
> Does `holotable.exe` support `Icons: Defensive Shield` icons? I see you are changing it from `Icons: Defensive Shields`.
> 
> There are some places where you are changing `Set: Virtual Defensive Shields` to `Icons: Defensive Shield`, I believe that is a bulk-change mistake.
> 
> You are removing `Ability, Ability, Ability (V) (3)`
> 
> ```
> card "/starwars/Virtual0-Dark/t_abilityabilityability" "•Ability, Ability, Ability (V) (3)\nDark 
> ```

Thanks, Devon!

**Aurra Sing With Blaster Rifle (AI)** has no image file in **Images-HT\starwars\Virtual12-Dark\large**, unlike **Admiral Trench** from the same set does.  So I removed her.

Who can confirm **Dark Jedi Master** is supported by Holotable?  Are you concerned with the casing?  It is consistent with other type/subtype casings.

The JSON files recently added **Defensive Shield** icons where appropriate, so my parser included them.  Who can confirm it is supported by Holotable?  If it is not, it is a simple thing for me to update my parser and remove them from this PR.

In the JSON file, the set names are actually, for example, **Virtual Set 12**.  Holotable just calls them **Set 12**.  The PDF file and titles call them **Set 12**.  The folder for images on disk calls it Virtual12-Light and Virtual12-Dark.  I tried make my parser reconcile all those differences.  Do you have examples of **Set: Virtual Defensive Shields** to **Icons: Defensive Shield**?  I'll take that example and see what the data and the parser think and if I've made a mistake or if I'll be making a recommendation.

Finally, **Ability, Ability, Ability (V)** was blanked per **https://www.starwarsccg.org/resources/virtual-slips/**.  So I removed it and a few others cards.

**Comment by EchoBaseTrooper** [comment]
Have you tried opening your edited cdf files in Holodeck? It crashes when I try.

Dark Jedi Master instead of DARK JEDI MASTER is fine. Both exist in the current cdf.

Technically the existing Aurra Sing With Blaster Rifle image is the AI image (it uses the AI Aurra Sing card as the underlying card). I don't think the non-AI image was ever created.

**Comment by DevoKun** [comment]
`holotable.exe` will crash if the `bullet` (•) format is incorrect.
The file needs to be `windows-1252` encoded with a `0x95` bullet. There is some documentation about the `bullet` (•) requirements in the git repo: https://github.com/swccgpc/holotable#file-editors
The script `fix_bullets.py` is run as a GitHub Action to automatically fix the bullets. The current pull request does not have the correct bullet character encoding.
I opened a [pull request on Ron's repo](https://github.com/ronhowe/holotable/pull/1) that will fix the bullets in his pull request for testing.
If you want to test with `holotable.exe`, [use the files from my updates to Ron's PR](https://github.com/ronhowe/holotable/pull/1/files)

**Comment by ronhowe** [comment]
I accepted your PR and pushed the changes to this branch/PR.

I'm at work now.  So I'll have to do some testing tonight.

I always assumed that Holotable was crashing because the hashes were incorrect.  I knew there were definitely encoding considerations to be made, but I thought I had done that correctly.  Lessons learned for the (Set 13) future.

**Comment by ronhowe** [comment]
Would ya'll be opposed to me closing this PR and submitting much smaller PRs?

The first one I would submit is Set 13 support.  Everything else after would be small PRs address small issues.

I don't mind redoing the work.  My goal is quality (and sanity) over speed.

**Comment by ronhowe** [comment]
> Would ya'll be opposed to me closing this PR and submitting much smaller PRs?
> 
> The first one I would submit is Set 13 support. Everything else after would be small PRs address small issues.
> 
> I don't mind redoing the work. My goal is quality (and sanity) over speed.

To be clear, I'm almost in favor of this for sanity.  :)

**Comment by DevoKun** [comment]
That's up to you. I feel like we are very close to getting this PR merged. I am going slow because I want to ensure that `holotable.exe` continues to function. Programmatically generating the `CDF` files from the json database is the future direction I want holotable to go, so the work needs to be done at some point to understand how picky, or not, the app is.
If you would rather merge in set 13 first that is fine too. I would recommend that instead of closing this PR, and losing the history in this thread so far, you create a new branch with just set 13 changes. You can then merge in those changes to this PR and we can keep going forward.
_(Hit me up on Slack if you need help with the cross branch merging.)_

**Comment by ronhowe** [comment]
I'll archive this thread through screen copy/paste, but I am going to start fresh and re-fork.

I didn't start my fork off the right way (by using a non-master branch for PR) and I've learned some other things about git too.

I'd like to start clean where every PR I submit is small, completed through the right PR process, and (if possible) personally verified that the CDF files work with Holotable.

I'll get started tonight.

**Pull request closed without merging**
